### ISSUE TITLE
Let'supgrade/Javascript-Essentials

### ISSUE THREAD

**Issue by KashafK** [LetsUpgrade/Javascript-Essentials#2]

**Comment by SameeranP** [comment]
What's the issue?

**Comment by ghost** [comment]
I want to complete a JavaScript course. I have a network problem because I
am in the village. I want to complete my assignment. I didn't know how to
use GitHub and Repel It so I couldn't finish my assignment.

**Comment by Ngowi-Inc** [comment]
Hello, I'm sorry because I am learning about Github too. I am not that
experienced

**Comment by ghost** [comment]
Hii sir/madam
      Please help me..How to use github and repel it.i want to complete my
assignment .

>
